
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bianca
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    private File file;
    private Image image = null;
    private BufferedImage buffered;
    private BufferedImage image_response = null;

    private ServerImage serverImage = null;
    private ImageProcessing client = null;

    public TelaInicial() {
        initComponents();
        client = new ImageProcessing();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        gerenateMask = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        applyMask = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centerLine = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        centerCol = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        txtTipo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        txtPath1 = new javax.swing.JTextField();
        btnChoose1 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSend2 = new javax.swing.JButton();
        gerenateMask1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        applyMask1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtPath2 = new javax.swing.JTextField();
        btnChoose2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        txtTipo2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTipo3 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        txtSituacao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTipo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtTipo.setText("New");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("Omnidirectional");

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        txtPath.setEditable(false);
        txtPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPathActionPerformed(evt);
            }
        });

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        btnSend.setText("Panoramic");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel4.add(btnSend);

        gerenateMask.setText("Generate mask");
        gerenateMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenateMaskActionPerformed(evt);
            }
        });
        jPanel4.add(gerenateMask);

        jButton1.setText("Bird's eye");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        applyMask.setText("Apply mask");
        applyMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyMaskActionPerformed(evt);
            }
        });
        jPanel4.add(applyMask);

        jButton4.setText("Download");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Line");

        centerLine.setText("1463");
        centerLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerLineActionPerformed(evt);
            }
        });

        jLabel5.setText("Col");

        centerCol.setText("2094");
        centerCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerColActionPerformed(evt);
            }
        });

        jButton10.setText("Calibrate");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(centerLine, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(centerCol, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(centerLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centerCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChoose))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtTipo)
                                    .addGap(435, 435, 435)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChoose)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTipo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addGap(61, 61, 61)
                .addComponent(jButton4)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("by image", jPanel1);

        label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTipo1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtTipo1.setText("New");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setText("Omnidirectional");

        label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPath1.setEditable(false);
        txtPath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPath1ActionPerformed(evt);
            }
        });

        btnChoose1.setText("Choose");
        btnChoose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoose1ActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        btnSend2.setText("Panoramic");
        btnSend2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSend2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSend2);

        gerenateMask1.setText("Generate mask");
        gerenateMask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenateMask1ActionPerformed(evt);
            }
        });
        jPanel3.add(gerenateMask1);

        jButton7.setText("Register");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.setText("Bird's eye");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        applyMask1.setText("Apply mask");
        applyMask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyMask1ActionPerformed(evt);
            }
        });
        jPanel3.add(applyMask1);

        jButton5.setText("Download");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(62, 62, 62)
                                .addComponent(txtTipo1))
                            .addComponent(txtPath1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChoose1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTipo1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnChoose1)
                        .addGap(10, 10, 10)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("by id", jPanel2);

        txtPath2.setEditable(false);
        txtPath2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPath2ActionPerformed(evt);
            }
        });

        btnChoose2.setText("Choose");
        btnChoose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoose2ActionPerformed(evt);
            }
        });

        jButton9.setText("Register");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton2.setText("Detect boxes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Detect points");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "Y", "W", "H"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        label5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTipo2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtTipo2.setText("Detection table");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setText("Image");

        txtTipo3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtTipo3.setText("Detection");

        txtId1.setEditable(false);
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTipo2))))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtPath2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnChoose2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addContainerGap(296, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addContainerGap(892, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChoose2)
                    .addComponent(txtPath2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo3)
                    .addComponent(txtTipo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGap(42, 42, 42)))
        );

        jTabbedPane1.addTab("detection", jPanel5);

        txtSituacao.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtSituacao.setText("...");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setText("SIMULATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1376, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtSituacao))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSituacao)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Select one image");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagem", "png", "jpg", "bmp");

        jfc.setFileFilter(ext);

        int r = jfc.showOpenDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            image = null;
            try {
                image = ImageIO.read(file);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Impossible to load");
            } finally {
                System.out.println(file.getAbsolutePath());
                txtPath.setText(file.getAbsolutePath());
                buffered = (BufferedImage) image;
                label1.setIcon(new ImageIcon(Utils.getScaledDimension(buffered, label1.getHeight(), label1.getWidth())));
            }
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        if (image != null) {
            txtSituacao.setText("Loading...");
            txtTipo.setText("Panoramic");
            long tempoInicial = System.currentTimeMillis();
            Image panoramica = client.getPanoramicImage(image);
           System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            System.out.println(panoramica.getHeight(null));
            label2.setIcon(new ImageIcon(Utils.getScaledDimension(panoramica, label2.getHeight(), label2.getWidth())));
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Please select one image");
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtTipo.setText("Bird's eye");
        if (image != null && Retification.getParametersAngle().size()>0) {
            txtSituacao.setText("Loading...");
            Image bird = null;
             long tempoInicial = System.currentTimeMillis();
            try {
                bird = Retification.retify(image);
            } catch (Exception ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
           System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            
            label2.setIcon(new ImageIcon(Utils.getScaledDimension(bird, label2.getHeight(), label2.getWidth())));
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Please choose the image id and calibrate");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathActionPerformed

    private void txtPath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPath1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPath1ActionPerformed

    private void btnChoose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoose1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Select one image");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagem", "png", "jpg", "bmp");

        jfc.setFileFilter(ext);

        int r = jfc.showOpenDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            image = null;
            try {
                image = ImageIO.read(file);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Impossible to load");
            } finally {
                System.out.println(file.getAbsolutePath());
                txtPath1.setText(file.getAbsolutePath());
                buffered = (BufferedImage) image;
                label3.setIcon(new ImageIcon(Utils.getScaledDimension(buffered, label3.getHeight(), label3.getWidth())));
            }
        }
    }//GEN-LAST:event_btnChoose1ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (image != null) {
            txtSituacao.setText("Loading...");
             long tempoInicial = System.currentTimeMillis();
            serverImage = new ServerImage(image);
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            
            String id = serverImage.getId();
            
            txtId.setText(id);
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Select the image first");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnSend2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSend2ActionPerformed
        if (serverImage != null) {
            txtSituacao.setText("Loading...");
            txtTipo1.setText("Panoramic");
             long tempoInicial = System.currentTimeMillis();
            Image panoramica = serverImage.getPanoramicImage();
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            System.out.println(panoramica.getHeight(null));
            label4.setIcon(new ImageIcon(Utils.getScaledDimension(panoramica, label4.getHeight(), label4.getWidth())));
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the image id");
        }
    }//GEN-LAST:event_btnSend2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        txtTipo1.setText("Bird's eye");
        if (serverImage != null && Retification.getParametersAngle().size()>0) {
            txtSituacao.setText("Loading...");
            Image bird = null;
             long tempoInicial = System.currentTimeMillis();
            try {
                bird = Retification.retify(serverImage.getId());
            } catch (Exception ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            
            label4.setIcon(new ImageIcon(Utils.getScaledDimension(bird, label4.getHeight(), label4.getWidth())));
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the image id and calibrate");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void centerLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centerLineActionPerformed

    private void centerColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centerColActionPerformed

    private void gerenateMask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenateMask1ActionPerformed
        if (serverImage != null) {
            txtSituacao.setText("Loading...");
            System.out.println("Gerando mascara...");
            serverImage.generateMask();
            System.out.println("mascara gerada");
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the image id");
        }
    }//GEN-LAST:event_gerenateMask1ActionPerformed

    private void gerenateMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenateMaskActionPerformed
        System.out.println("Gerando mascara...");
         long tempoInicial = System.currentTimeMillis();
        client.generateMask();
       System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));

    }//GEN-LAST:event_gerenateMaskActionPerformed

    private void applyMask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyMask1ActionPerformed
        if (serverImage != null) {
            txtTipo1.setText("Masked");
            txtSituacao.setText("Loading...");
            long tempoInicial = System.currentTimeMillis();
            Image panoramica = serverImage.useMask();
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            System.out.println(panoramica.getHeight(null));
            label4.setIcon(new ImageIcon(Utils.getScaledDimension(panoramica, label4.getHeight(), label4.getWidth())));
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the image id");
        }
    }//GEN-LAST:event_applyMask1ActionPerformed

    private void applyMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyMaskActionPerformed

        if (image != null) {
            txtSituacao.setText("Loading...");
            txtTipo.setText("Masked");
             long tempoInicial = System.currentTimeMillis();
            Image masked = client.useMask(image);
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            System.out.println(masked.getHeight(null));
            label2.setIcon(new ImageIcon(Utils.getScaledDimension(masked, label2.getHeight(), label2.getWidth())));
            txtSituacao.setText("Done!");
            //image_response = (BufferedImage) masked;
        } else {
            JOptionPane.showMessageDialog(this, "Please select one image");
        }

    }//GEN-LAST:event_applyMaskActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (image_response != null) {
            try {
                File outputfile = new File("saved.png");
                ImageIO.write(image_response, "png", outputfile);
            } catch (IOException e) {
                System.err.println("Failed");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtPath2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPath2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPath2ActionPerformed

    private void btnChoose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoose2ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Select one image");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagem", "png", "jpg", "bmp");

        jfc.setFileFilter(ext);

        int r = jfc.showOpenDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            image = null;
            try {
                image = ImageIO.read(file);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Impossible to load");
            } finally {
                System.out.println(file.getAbsolutePath());
                txtPath2.setText(file.getAbsolutePath());
                buffered = (BufferedImage) image;
                label5.setIcon(new ImageIcon(Utils.getScaledDimension(buffered, label5.getHeight(), label5.getWidth())));
            }
        }
    }//GEN-LAST:event_btnChoose2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (image != null) {
            txtSituacao.setText("Loading...");
            serverImage = new ServerImage(image);
            String id = serverImage.getId();
            txtId1.setText(id);
            txtSituacao.setText("Done!");
        } else {
            JOptionPane.showMessageDialog(this, "Select the image first");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (serverImage != null) {
             txtSituacao.setText("Loading...");
            txtTipo3.setText("Objects");
             long tempoInicial = System.currentTimeMillis();
            Image panoramica = serverImage.getImageWithBoxes();
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            
            System.out.println(panoramica.getHeight(null));
            label6.setIcon(new ImageIcon(Utils.getScaledDimension(panoramica, label6.getHeight(), label6.getWidth())));
            tempoInicial = System.currentTimeMillis();
            panoramica = client.getImageWithBoxes(image) ;
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            txtSituacao.setText("Done!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the image id");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if (serverImage != null) {
            txtTipo3.setText("Objects");
             long tempoInicial = System.currentTimeMillis();
            DetectedObjectsList objects = serverImage.getObjectsDetected();
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setNumRows(0);
            for(DetectedObject d : objects.getList()){
                dtm.addRow(new Object[]{d.getX(), d.getY(), d.getWidth(), d.getHeight()});
            }
            tempoInicial = System.currentTimeMillis();
             objects  = client.getObjectsDetected(image) ;
            System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
            
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the image id");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int centerL = Integer.parseInt(centerLine.getText());
        int centerC = Integer.parseInt(centerCol.getText());
        long tempoInicial = System.currentTimeMillis();
        Retification.generateParams(centerC, centerL);
        System.out.println("o metodo executou em " + ((double) (System.currentTimeMillis() - tempoInicial)/1000));
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyMask;
    private javax.swing.JButton applyMask1;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnChoose1;
    private javax.swing.JButton btnChoose2;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSend2;
    private javax.swing.JTextField centerCol;
    private javax.swing.JTextField centerLine;
    private javax.swing.JButton gerenateMask;
    private javax.swing.JButton gerenateMask1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtPath1;
    private javax.swing.JTextField txtPath2;
    private javax.swing.JLabel txtSituacao;
    private javax.swing.JLabel txtTipo;
    private javax.swing.JLabel txtTipo1;
    private javax.swing.JLabel txtTipo2;
    private javax.swing.JLabel txtTipo3;
    // End of variables declaration//GEN-END:variables
}
